# Generated by Django 5.1.6 on 2025-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="stockdata",
            unique_together={("stock", "date")},
        ),
    ]
