# Generated by Django 5.1.6 on 2025-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_stockdata_dividend_per_share_stockdata_eps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="close_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="eps",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="high_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="low_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="net_debt",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="net_income",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="normalized_income",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="open_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="repurchase_stock",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="total_assets",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="total_revenue",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
    ]
