// src/components/MyWayToProgramming.js
import React from "react";
import "./Code.css"; // Import opcjonalnego pliku CSS dla stylizacji

const Code = () => {
  // Zmień poniżej ścieżkę do swojego zdjęcia
  const profilePhoto = "/images/profile_pic.jpeg";

  return (
    <section className="my-way">
      {/* Zdjęcie profilowe na górze */}
      <div className="profile-photo-container">
        <img src={profilePhoto} alt="My Profile" className="profile-photo" />
      </div>

      {/* Bio – tekst opisujący Twoją drogę do programowania */}
      <div className="bio">
        <h1>My Way to Programming</h1>
        <p>
        My journey into IT was paved by my experiences in the financial markets. 
        Ten years ago, while working as a quality inspector at one of the leading automotive companies in UK, 
        I met a colleague at a social gathering who was a professional trader in the financial markets. 
        His intelligence and the passion with which he spoke about his work ignited my curiosity. Soon after, 
        I began dipping my toes into forex trading, precious metals, and the stock market. 
        I quickly realized that the analytical tools I was familiar with were not sufficient to process the enormous amount of data generated by these markets.
        </p>

        {/* Przykładowa grafika między blokami tekstu */}
        <div className="bio-image">
          <img src="/images/python_personification.webp" alt="First Step" />
        </div>

        <p>
        As I delved deeper into IT, I discovered the endless analytical possibilities that come from merging technical expertise with financial acumen.
        Every measurable success in the markets, achieved through my own meticulously prepared analyses, only fueled my desire to learn more.
        Over time, I fell into what felt like a “rabbit hole” – the more I learned, the more I became aware of the vast ocean of knowledge still left to explore.
        Yet I realized that this sense of endless learning is an intrinsic part of being an IT professional. In a rapidly evolving industry, it is impossible to master every secret, and anyone driven by a natural ambition for growth will never be fully satisfied with their current skill set.
        Today, I embrace this perpetual pursuit of knowledge as the most beautiful aspect of my career – a journey where the horizon always remains just out of reach, keeping every day as fascinating as the first.
        </p>
      </div>
    </section>
  );
};

export default Code;