# Generated by Django 5.1.6 on 2025-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_token",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
