# Generated by Django 5.1.6 on 2025-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activation_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
